spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giuaki
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: caoky.sonha@gmail.com
    password: 'iisrdsbtaljjucag'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
