spring:
  datasource:

    url: jdbc:mysql://mysql-26154030-caoky-de8f.g.aivencloud.com:22423/defaultdb
    username: avnadmin
    password: 'AVNS_rK2vnAik3WpBICGT3ZS'
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: caoky.sonha@gmail.com
    password: 'iisrdsbtaljjucag'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
